In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [ ]:
df = pd.read_csv('/content/job_salary_prediction_dataset.csv')

In [ ]:
df

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  object
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  object
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  object
 5   company_size      250000 non-null  object
 6   location          250000 non-null  object
 7   remote_work       250000 non-null  object
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(4), object(6)
memory usage: 19.1+ MB

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['job_title']= le.fit_transform(df['job_title'])
df['education_level']= le.fit_transform(df['education_level'])
df['industry']= le.fit_transform(df['industry'])
df['company_size']= le.fit_transform(df['company_size'])
df['location']= le.fit_transform(df['location'])
df['remote_work']= le.fit_transform(df['remote_work'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_title         250000 non-null  int64
 1   experience_years  250000 non-null  int64
 2   education_level   250000 non-null  int64
 3   skills_count      250000 non-null  int64
 4   industry          250000 non-null  int64
 5   company_size      250000 non-null  int64
 6   location          250000 non-null  int64
 7   remote_work       250000 non-null  int64
 8   certifications    250000 non-null  int64
 9   salary            250000 non-null  int64
dtypes: int64(10)
memory usage: 19.1 MB

In [ ]:
df

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,0,10,0,2,4,2,3,0,2,109413
1,5,5,0,17,9,3,0,1,0,93764
2,8,18,4,4,6,2,6,1,1,148123
3,2,19,4,13,7,2,1,2,0,189123
4,10,15,0,7,5,1,7,2,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,11,17,4,2,9,0,3,1,1,127791
249996,8,20,4,7,9,4,5,1,2,154593
249997,2,1,0,12,7,0,3,2,0,75988
249998,6,0,2,2,0,3,7,0,5,90467
249999,5,16,1,2,8,2,8,1,5,133084

In [ ]:
x = df.drop('salary',axis=1)
y = df['salary']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = model.predict(x_test)
r2 = r2_score(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
print(r2)
print(mse)

0.4559758296725783
756119410.2741928

In [ ]:
new_data = (6 ,0 ,2 ,2 ,0 ,3 ,7 ,0 ,5)

In [ ]:
data_as = np.asarray(new_data)
data_reshaped = data_as.reshape(1,-1)

In [ ]:
pred = model.predict(data_reshaped)
print('salary prediction:',pred)

salary prediction: [108363.87610769]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(